services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: league_db
    volumes:
      - ./db/champions_db.sql:/docker-entrypoint-initdb.d/champions_db.sql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - mynetwork

  db_loader:
    build: ./db_loader
    depends_on:
      - mysql  # Assure-toi que db_loader dépend de mysql
    networks:
      - mynetwork
    restart: "no"

  league_api:
    build: ./league_api
    depends_on:
      - mysql  # Assure-toi que league_api dépend de mysql
      - db_loader  # Assure-toi que league_api dépend de db_loader
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: league_db
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    restart: on-failure
    # Wait-for-it pour garantir que db_loader a bien terminé avant de lancer l'API
    command: ["./wait-for-it.sh", "db_loader:3000", "--", "node", "api.js"]

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
