services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: league_db
    volumes:
      - ./db/champions_db.sql:/docker-entrypoint-initdb.d/champions_db.sql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - mynetwork

  db_loader:
    build: ./db_loader
    depends_on:
      - mysql  # Assure-toi que db_loader dépend de mysql
    networks:
      - mynetwork
    restart: "no"

  league_api:
    build: ./league_api
    depends_on:
      db_loader:
        condition: service_completed_successfully  # Démarrer après db_loader
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: league_db
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    restart: on-failure

  frontend:
    build: ./frontend
    depends_on:
      - league_api
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
